Fix packaging

diff --git a/packages/ruby/packaging b/packages/ruby/packaging
--- a/packages/ruby/packaging
+++ b/packages/ruby/packaging
@@ -9,42 +9,32 @@ set -u # report the usage of uninitialized variables
 CPUS=$(grep -c ^processor /proc/cpuinfo)
 
 export HOME=/var/vcap
+export RUBY_VERSION=`ls -r ruby/ruby-* | sed 's/ruby\/ruby-\(.*\)\.tar\.gz/\1/' | head -1`
+export RUBYGEMS_VERSION=`ls -r ruby/rubygems-* | sed 's/ruby\/rubygems-\(.*\)\.tgz/\1/' | head -1`
+export BUNDLER_VERSION=`ls -r ruby/bundler-* | sed 's/ruby\/bundler-\(.*\)\.gem/\1/' | head -1`
 export LIBYAML_PATH=/var/vcap/packages/libyaml
 export ZLIB_PATH=/var/vcap/packages/zlib
 
-echo "Extracting autoconf..."
-tar xvf ruby/autoconf.tar.gz 
+# compile and install ruby
+echo "Compiling and installing ruby..."
+tar xfz ruby/ruby-$RUBY_VERSION.tar.gz
+cd ruby-$RUBY_VERSION
+./configure --prefix=${BOSH_INSTALL_TARGET} --enable-shared --disable-install-doc --with-opt-dir=$LIBYAML_PATH --with-opt-dir=$ZLIB_PATH
+make -j${CPUS} && make install
+echo "Finished installing ruby."
+cd ..
 
-echo "Extracting ruby..."
-tar xvf ruby/ruby.tar.gz
+# compile and install rubygems
+echo "Installing rubygems..."
+tar xfz ruby/rubygems-$RUBYGEMS_VERSION.tgz
+cd rubygems-$RUBYGEMS_VERSION
+${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
+if [[ $? != 0 ]] ; then
+  echo "Cannot install rubygems"
+  exit 1
+fi
+echo "Finished installing rubygems."
+cd ..
 
-echo "Extracting rubygems..."
-tar xvf ruby/rubygems.tar.gz
-
-echo "Extracting bundler..."
-tar xvf ruby/bundler.tar.gz
-
-echo "Building autoconf..."
-pushd autoconf-* > /dev/null
-  ./configure
-  make
-  make install
-popd > /dev/null
-
-echo "Building ruby..."
-pushd ruby-* > /dev/null
-  ./configure --prefix=${BOSH_INSTALL_TARGET} --enable-shared --disable-install-doc --with-opt-dir=$LIBYAML_PATH --with-opt-dir=$ZLIB_PATH
-  make -j${CPUS} && make install
-popd > /dev/null
-
-echo "Building rubygems..."
-  pushd rubygems-* > /dev/null
-  ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
-  fi
-popd > /dev/null
-
-echo "Building bundler..."
-pushd bundler-* > /dev/null
-  ${BOSH_INSTALL_TARGET}/bin/gem build bundler.gemspec
-  ${BOSH_INSTALL_TARGET}/bin/gem install *.gem --no-ri --no-rdoc
-popd > /dev/null
+# install the bundler version
+${BOSH_INSTALL_TARGET}/bin/gem install ruby/bundler-${BUNDLER_VERSION}.gem --no-ri --no-rdoc
